### ISSUE TITLE
这样混淆 会被拒吗

### ISSUE THREAD

**Issue by DavidCap** [CoderMJLee/MJCodeObfuscation#2]
按照这种方式混淆，不知道 会不会被苹果拒，之前弄过混淆 被拒过。。。。

**Comment by CoderMJLee** [comment]
是的哦，大面积混淆有风险

**Comment by DavidCap** [comment]
那如果要 应用的话，是应该小部分核心代码混淆，是这个意思吧。

**Comment by CoderMJLee** [comment]
是的，把需要混淆的核心部分处理一下。其实也没必要整个项目都混淆哈

**Comment by DavidCap** [comment]
谢谢 MJ老师，看你视频 入坑的。
不知道这个 project，有没有什么 todolist，可以参与进来。

**Comment by CoderMJLee** [comment]
刚好上课要讲到这块的知识点，所以写了这个小工具辅助一下哈，就是个小Demo
